### PR TITLE
#18353 should we copy every...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

#18353 should we copy every docker.io/centos/postgresql-96-centos7:9.6 update to a matching quay.io/eclipse/che-postgres:7.y.z tag? is this even used anywhere???

Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit messasge above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
Usage is there https://github.com/eclipse/che-operator/pull/569/files

**Comment by nickboldt** [comment]
I've merged https://github.com/eclipse/che-release/pull/11 but this one is now in need of rebasing, if we want it.

**Comment by tolusha** [comment]
@nickboldt 
We can't do it
https://quay.io/repository/eclipse/che-postgres?tag=latest&tab=tags
They are a bit different images than just a copy

**Comment by tolusha** [comment]
https://github.com/eclipse/che/blob/master/dockerfiles/postgres/Dockerfile#L13

**Comment by nickboldt** [comment]
OK, but we're not USING those images in any way, right? so replacing them with something we CAN and WILL use would be good.

We used to build this image every week in https://github.com/eclipse/che-release/pull/11/files but I disabled that since it was stated that no one is using it in deployments, tests, etc.

**Comment by nickboldt** [comment]
couldn't we have `--installer helm` work with the official postgres image too?

**Comment by nickboldt** [comment]
I see that your closing this means "we will not investigate". :)

**Pull request closed without merging**
