### PR TITLE
add GH action for sending notifications of release status / reminders about milestone cleanup

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

add GH action for sending mail to che-dev list

Change-Id: I9fb886002932b68f8af72d1389c44f11901a09c6
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?

* https://github.com/eclipse/che/issues/17579
* https://github.com/eclipse/che/issues/17748

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
If this doesn't work, we could try using a simple bash script, assuming mail or mailx is installed:

```
echo "...... email body here ...... " > mailbody.tmp
if [[ -x /bin/mailx ]]; then 
    /bin/mailx -s "''' + mailSubject + '''" -c "''' + CCrecipients + '''" -r "''' + sender + '''" "''' + TOrecipients + '''" < mailbody.tmp
else 
    /bin/mail -s "''' + mailSubject + '''" "''' + TOrecipients + '''" -c"''' + CCrecipients + '''" -- -f"''' + sender + '''" < mailbody.tmp
fi
rm -f mailbody.tmp
```
see full example in https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.6-rhel-8/dependencies/send-email-qe-build-list.Jenkinsfile#L67-L76

**Comment by mkuznyetsov** [comment]
looks like it's gonna be on hold, until we will find appropriate smtp username&password

**Review by mkuznyetsov — CHANGES_REQUESTED** [review]
need smtp username & password that can be used on "CI"

**Comment by nickboldt** [comment]
MM notification done in https://github.com/eclipse/che/issues/18906

**Pull request closed without merging**
