### PR TITLE
seems like we set the wrong versions of...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

seems like we set the wrong versions of parent pom (CHE_VERSION vs. VERSION_CHE_PARENT)

Change-Id: Id69d09f27878fad3620c976eef7208dc3f2c00d7
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit messasge above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
In 7.23.0 tag of eclipse/che, I see there's a reference to a non-existant parent pom from typescript-dto/dto-pom.xml:

image

in master branch it's no better:

image

This is because the che-parent is (in master):

```
    <groupId>org.eclipse.che.parent</groupId>
    <artifactId>maven-parent-pom</artifactId>
    <version>7.15.0-SNAPSHOT</version>
```
and in 7.23.x branch or che-parent:

```
    <groupId>org.eclipse.che.parent</groupId>
    <artifactId>maven-parent-pom</artifactId>
    <version>7.15.0-SNAPSHOT</version>
```

**Comment by nickboldt** [comment]
@benoitf do you know how the `che typescript DTO` is used? Seems that we're publishing a pom that can't be built, so I suspect it's not being used...

**Comment by benoitf** [comment]
It's not the pom that is used directly, it's the npmjs artifact published by this pom: https://www.npmjs.com/package/@eclipse-che/api

It seems since 7.18.1 there is an issue publishing it BTW

**Comment by benoitf** [comment]
about pom.xml: https://github.com/eclipse/che/commit/0048a57bd89de23fa44853cabd998c519bddf898#diff-20ebddb0496d12fe03f0bdea9fe1ecfc8fa6c6a3bfb032032a119af711f4e4d7

**Pull request merged**
